[network]
cluster = "mainnet-beta"
accounts_fetching = true

[programs]
saros_dlmm = "LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo"

[accounts]
pools = [
  "ADPKeitAZsAeRJfhG2GoDrZENB3xt9eZmggkj7iAXY78",  # SAROS/USDC Pool A
  "GNDi5xLZm26vpVyBbVL9JrDPXR88nQfcPPsmnZQQcbTh",  # SAROS/USDC Pool B
]
